version: 1
services:
  - name: intel-agent-web
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DAILY_API_LIMIT
        value: "20"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
    dockerCommand: "./start.sh"

  - name: intel-agent-worker
    type: worker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "celery -A config worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: SECRET_KEY
        generateValue: true
      - key: DAILY_API_LIMIT
        value: "20"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
