# Generated by Django 4.2.16 on 2026-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='competitor',
            name='current_task_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
