# Generated by Django 4.2.16 on 2026-04-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_competitor_current_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsnapshot',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.CreateModel(
            name='DiscoveredPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('page_type', models.CharField(choices=[('pricing', 'Pricing'), ('features', 'Features'), ('blog', 'Blog'), ('about', 'About'), ('careers', 'Careers'), ('product', 'Product'), ('other', 'Other')], default='other', max_length=20)),
                ('is_tracked', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_pages', to='competitors.competitor')),
            ],
            options={
                'ordering': ('-discovered_at',),
                'unique_together': {('competitor', 'url')},
            },
        ),
    ]
