# Generated by Django 4.2.16 on 2026-04-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='digest_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_digest_enabled',
        ),
    ]
